COMMON:
  save_collected: True

  TIMESTEP: 0.004 # 0.002 * 20
  TRAINFILE: train.csv
  TESTFILE: test.csv
  TESTSET_MULTIPLIER: 2 # |Trainset| = |Trainset|*multiplier
  BATCH_SIZE: 128
  EARLY_STOPPING: 16000

  ALL_MODEL_CONFIGS: [PIDNN_32000, PIDNN_64000, PIDNN_128000, FF_32000, FF_64000, FF_128000, FF_256000]
  ALL_DATA_CONFIGS: [SIMULATION_30_40, SIMULATION_80_90]
  ALL_NOISE_CONFIGS: [0.00, 0.10]

  MODEL_CONFIGS: [FF_32000, FF_64000, FF_128000, PIDNN_32000, PIDNN_64000, PIDNN_128000]
  DATA_CONFIGS: [SIMULATION_30_40, SIMULATION_80_90]
  NOISE_CONFIGS: [0.00, 0.10]

  # ALPHA: [0.01, 0.1, 1, 10, 100]
  # BETA: [0.01, 0.1, 1, 10, 100]
  ALPHA: [0.0005]
  BETA: [0.0005]
  SEEDS: [2314, 4132]

  POINT_LOSS_COEFFS: [0.7, 0.8, 0.9]
  # THETA_LOSS_COEFF: 0.2 # Taken as 1 - POINT_LOSS_COEFF
  INIT_TIMESTEPS: 20

  SAVE_PLOT: True
  SAVE_MODEL: True
  DATASET_CACHING: False
  MODEL_CACHING: True
  CUDA_ENABLED: True
  ANOMALY_DETECTION: False

  save_debug: False
  render: False

  g: 9.81
  m1: 2
  m2: 1
  l1: 2
  l2: 1

# MODEL TEMPLATES

PIDNN:
  model_name: pidnn
  num_layers: 8
  neurons_per_layer: 20
  training_is_border: False
  take_differential_points: True
  num_datadriven: -1  # To be filled by reader
  num_collocation: -1 # Filled as collocation_multiplier*num_datadriven
  # collocation_multiplier: [1, 5, 10] # Hyperparameter for collocation points
  collocation_multiplier: [4] # Hyperparameter for collocation points
  differential_order: 3

FF:
  model_name: ff
  num_layers: 16
  neurons_per_layer: 40
  training_is_border: False
  take_differential_points: False
  num_datadriven: -1  # To be filled by reader
  num_collocation: 0
  collocation_multiplier: [0]

# DATA RANGES

SIMULATION_30_40:
  toy_data: False

  TRAIN_ITERATIONS: 10000
  TRAIN_THETA_VALUES: 6  # Actual values = n^2 because n for theta1 and n each for theta2
  TRAIN_THETA_START: 30.0
  TRAIN_THETA_END: 40.0

  datadir: ./Data/simulation_30_40/
  testdirs: []

SIMULATION_80_90:
  toy_data: False

  TRAIN_ITERATIONS: 10000
  TRAIN_THETA_VALUES: 6  # Actual values = n^2 because n for theta1 and n each for theta2
  TRAIN_THETA_START: 80.0
  TRAIN_THETA_END: 90.0

  datadir: ./Data/simulation_80_90/
  testdirs: []
