COMMON:
  save_collected: True

  TIMESTEP: 0.04 # 0.002 * 20
  TRAINFILE: train.csv
  TESTFILE: test.csv
  TESTSET_MULTIPLIER: 2 # |Trainset| = |Trainset|*multiplier
  BATCH_SIZE: 128
  EARLY_STOPPING: 6400

  ALL_MODEL_CONFIGS: [PIDNN_200, PIDNN_400, PIDNN_800, PIDNN_1600, PIDNN_3200, FF_200, FF_400, FF_800, FF_1600]
  ALL_DATA_CONFIGS: [SIMULATION_80_90, SIMULATION_150_170, SIMULATION_140_170]
  ALL_NOISE_CONFIGS: [0.00, 0.05, 0.10]

  MODEL_CONFIGS: [PIDNN_800]
  DATA_CONFIGS: [SIMULATION_80_90]
  NOISE_CONFIGS: [0.00]

  # ALPHA: [0.01, 0.1, 1, 10, 100]
  # BETA: [0.01, 0.1, 1, 10, 100]
  ALPHA: [0]
  BETA: [0]

  SAVE_PLOT: True
  SAVE_MODEL: True
  DATASET_CACHING: False
  MODEL_CACHING: False
  CUDA_ENABLED: False
  ANOMALY_DETECTION: False

  save_debug: False
  render: False

  g: 9.81
  m1: 2
  m2: 1
  l1: 2
  l2: 1

# MODEL TEMPLATES

PIDNN:
  model_name: pidnn
  num_layers: 8
  neurons_per_layer: 20
  training_is_border: False
  take_differential_points: True
  num_datadriven: -1  # To be filled by reader
  num_collocation: -1 # Filled as collocation_multiplier*num_datadriven
  # collocation_multiplier: [1, 5, 10] # Hyperparameter for collocation points
  collocation_multiplier: [7] # Hyperparameter for collocation points
  differential_order: 3

FF:
  model_name: ff
  num_layers: 8
  neurons_per_layer: 20
  training_is_border: False
  take_differential_points: False
  num_datadriven: -1  # To be filled by reader
  num_collocation: 0
  collocation_multiplier: [0]

# DATA RANGES

SIMULATION_80_90:
  toy_data: False

  TRAIN_ITERATIONS: 1000
  TRAIN_THETA_VALUES: 6  # Actual values = n^2 because n for theta1 and n each for theta2
  TRAIN_THETA_START: 80.0
  TRAIN_THETA_END: 90.0

  datadir: ./Data/simulation_80_90/
  testdirs: []

SIMULATION_150_170:
  toy_data: False

  TRAIN_ITERATIONS: 1000
  TRAIN_THETA_VALUES: 8
  TRAIN_THETA_START: 150.0
  TRAIN_THETA_END: 170.0

  datadir: ./Data/simulation_150_170/
  testdirs: []

SIMULATION_140_170:
  toy_data: False

  TRAIN_ITERATIONS: 1000
  TRAIN_THETA_VALUES: 10
  TRAIN_THETA_START: 140.0
  TRAIN_THETA_END: 170.0

  datadir: ./Data/simulation_140_170/
  testdirs: []
